baseURL = "https://gr0wing.com/"
languageCode = "en-us"
title = "Think, Improve, Change the world in the process."
theme = "mini"
ignoreLogs = ["warning-goldmark-raw-html"]

hasCJKLanguage = true

# [permalinks]
#   posts = "/blog/posts/:title/"
#   categories = "blog/categories/:title/"
#   about = "/blog/about/:title/"
#   privacy-policy = "/blog/privacy-policy/:title/"
#   subscribe = "/blog/subscribe/:title/"
#   uncopyright = "/blog/uncopyright/:title/"

# paginate= '3'
# googleAnalytics = "UA-123-45"
# disqusShortname = "anegg0"

[markup]
  [markup.highlight]
    guessSyntax = true
    style = "emacs"
  [markup.goldmark.renderer]
    unsafe = true

# [social]
#   github = "https://github.com/anegg0"
#   twitter = "https://twitter.com/anegg0"
#   stackoverflow = "https://stackoverflow.com/users/4518882/anegg0"

[params]
  author = "anegg0"
  bio = "Technical Writer/Software Engineer"
  description = "My Blog"
  # enableRSS = true
  # enableComments = true
  # enableGoogleAnalytics = true
  showToc = true
  showPowerBy = true
  math = false
  hiddenPostSummaryInHomePage = false
