baseURL = "https://gr0wing.com/"
languageCode = "en-us"
title = "Think, Improve, Change the world in the process."
theme = "mini"
ignoreLogs = ["warning-goldmark-raw-html"]

hasCJKLanguage = true

[markup]
  [markup.highlight]
    guessSyntax = true
    style = "emacs"
  [markup.goldmark.renderer]
    unsafe = true

[social]
  github = "https://github.com/anegg0"

[params]
  author = "anegg0"
  bio = "Technical Writer/Software Engineer"
  description = "My Blog"
  # enableRSS = true
  showToc = true
  showPowerBy = true
  math = false
  hiddenPostSummaryInHomePage = false
